import "./Features/AutoGFS"
import "./Features/CloakNotifications"
import "./Features/Commands"
import "./Features/FireFreezeTimer"
import "./Features/LeapHelper"
import "./Features/MaskSwap"
import "./Features/MinibossTracker"
import "./Features/PreEnterAlerts"
import "./Features/RemoveSelfieCamera"
import "./Features/Rift"
import "./Features/SupplyPrio"
import "./Features/TerminalWaypoints"
import "./Features/Terrorsounds"
import "./Features/Wish"
import "./firstload"
import "./Autoupdater"
import { branding, getModuleVersion } from "./utils/stuff"

branding(`Loaded version: ${getModuleVersion()}`)